# Configuration for TravisCI
# https://travis-ci.org/tony19-sandbox/logback-test-app

language: android

android:
  components:
  - tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew check

after_failure:
  - "[ -f app/build/outputs/lint-results-debug.xml ] && cat app/build/outputs/lint-results-debug.xml"
