# Configuration for TravisCI
# https://travis-ci.org/tony19-sandbox/logback-test-app

language: android

android:
  components:
  - tools
  - build-tools-27.0.3
  - android-27
  - android-15
  - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew check

after_failure:
  - "[ -f app/build/outputs/lint-results-debug.xml ] && cat app/build/outputs/lint-results-debug.xml"
