# Configuration for CircleCI
# https://circleci.com/gh/tony19-sandbox/logback-test-app

version: 2.1

jobs:
  build:
    docker:
      # cimg/android 2024.01.x ships JDK 17 (default) and Android platform 34
      - image: cimg/android:2024.01.1
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Java version
          command: java -version
      - run:
          name: Build
          command: ./gradlew assembleDebug assembleRelease --stacktrace
      - store_artifacts:
          path: app/build/outputs
          destination: outputs

workflows:
  build_and_test:
    jobs:
      - build
